-- PRO ERP 2.3.0 - Logo/Tiger tarzı kurumsal genişletme paketi
-- Mevcut tabloları silmez; yalnız yeni tablolar, görünüm ve güvenli yardımcı nesneler ekler.

create table if not exists public.erp_belge_baglantilari (
  baglanti_id bigint generated by default as identity primary key,
  kaynak_tipi text not null,
  kaynak_no text not null,
  hedef_tipi text not null,
  hedef_no text not null,
  cari_id bigint,
  cari_unvan text,
  aciklama text,
  created_at timestamptz default now()
);
create index if not exists idx_erp_belge_baglantilari_kaynak on public.erp_belge_baglantilari(kaynak_tipi, kaynak_no);
create index if not exists idx_erp_belge_baglantilari_hedef on public.erp_belge_baglantilari(hedef_tipi, hedef_no);

create table if not exists public.erp_kur_farki_fisleri (
  kur_farki_id bigint generated by default as identity primary key,
  tarih timestamptz default now(),
  cari_id bigint,
  cari_unvan text,
  para_birimi text not null,
  doviz_tutar numeric(18,4) default 0,
  eski_kur numeric(18,6) default 0,
  yeni_kur numeric(18,6) default 0,
  kur_farki numeric(18,2) default 0,
  belge_no text,
  durum text default 'KAYITLI',
  aciklama text,
  created_at timestamptz default now()
);
create index if not exists idx_erp_kur_farki_tarih on public.erp_kur_farki_fisleri(tarih desc);
create index if not exists idx_erp_kur_farki_cari on public.erp_kur_farki_fisleri(cari_id);

create table if not exists public.erp_sistem_kontrol_log (
  kontrol_id bigint generated by default as identity primary key,
  tarih timestamptz default now(),
  kontrol text not null,
  durum text not null,
  mesaj text,
  kullanici text
);

-- Vade takip nesnesi kurulumlara göre TABLE veya VIEW olabilir.
-- Hiç yoksa tablo oluşturulur; normal VIEW ise mevcut yapıya dokunulmaz.
do $$
declare
  v_relkind "char";
begin
  select c.relkind
    into v_relkind
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'erp_vade_takip';

  if v_relkind is null then
    execute $sql$
      create table public.erp_vade_takip (
        vade_id bigint generated by default as identity primary key,
        cari_id bigint,
        cari_unvan text,
        belge_tipi text,
        belge_id bigint,
        fatura_no text,
        yon text,
        fatura_tarihi date,
        vade_tarihi date,
        toplam_tutar numeric(18,2) default 0,
        odenen_tutar numeric(18,2) default 0,
        kalan_tutar numeric(18,2) default 0,
        gecikme_gun integer default 0,
        durum text default 'ACIK',
        created_at timestamptz default now()
      )
    $sql$;
    v_relkind := 'r';
    raise notice 'erp_vade_takip bulunamadı; TABLE olarak oluşturuldu.';
  elsif v_relkind = 'v' then
    raise notice 'erp_vade_takip mevcut bir VIEW; tabloya çevrilmedi ve VIEW korunuyor.';
  elsif v_relkind = 'm' then
    raise notice 'erp_vade_takip MATERIALIZED VIEW olarak mevcut.';
  else
    raise notice 'erp_vade_takip mevcut relation tipi: %', v_relkind;
  end if;

  -- Normal tablo/partitioned tablo/materialized view üzerinde index oluşturulabilir.
  if v_relkind in ('r','p','m') then
    execute 'create index if not exists idx_erp_vade_takip_vade on public.erp_vade_takip(vade_tarihi)';
    execute 'create index if not exists idx_erp_vade_takip_cari on public.erp_vade_takip(cari_id)';
  end if;
end $$;

-- Mizan görünümü: muhasebe fiş satırları üzerinden hesap bazında borç/alacak/bakiye.
create or replace view public.erp_mizan as
select
  s.hesap_kodu,
  coalesce(h.hesap_adi, '-') as hesap_adi,
  coalesce(h.hesap_tipi, '-') as hesap_tipi,
  coalesce(sum(s.borc),0)::numeric(18,2) as borc,
  coalesce(sum(s.alacak),0)::numeric(18,2) as alacak,
  (coalesce(sum(s.borc),0)-coalesce(sum(s.alacak),0))::numeric(18,2) as bakiye
from public.erp_muhasebe_fis_satirlari s
left join public.erp_hesap_plani h on h.hesap_kodu=s.hesap_kodu
group by s.hesap_kodu,h.hesap_adi,h.hesap_tipi;

-- Fiş satırı değiştiğinde üst fiş toplamlarını otomatik eşitle.
create or replace function public.erp_muhasebe_fis_toplam_guncelle()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_fis bigint;
begin
  if TG_OP = 'DELETE' then
    v_fis := old.fis_id;
  else
    v_fis := new.fis_id;
  end if;
  update public.erp_muhasebe_fisleri f
  set borc_toplam = coalesce((select sum(borc) from public.erp_muhasebe_fis_satirlari where fis_id=v_fis),0),
      alacak_toplam = coalesce((select sum(alacak) from public.erp_muhasebe_fis_satirlari where fis_id=v_fis),0)
  where f.fis_id=v_fis;
  if TG_OP = 'DELETE' then
    return old;
  end if;
  return new;
end $$;

drop trigger if exists trg_erp_muhasebe_fis_toplam on public.erp_muhasebe_fis_satirlari;
create trigger trg_erp_muhasebe_fis_toplam
after insert or update or delete on public.erp_muhasebe_fis_satirlari
for each row execute function public.erp_muhasebe_fis_toplam_guncelle();

-- Sık kullanılan yeni ERP alanlarında indeksler.
create index if not exists idx_erp_teklifler_cari_tarih on public.erp_teklifler(cari_unvan, tarih desc);
create index if not exists idx_erp_e_belgeler_durum on public.erp_e_belgeler(durum, olusturma_tarihi desc);
create index if not exists idx_erp_onaylar_durum on public.erp_onaylar(durum, olusturma_tarihi desc);
create index if not exists idx_erp_fiyat_kurallari_aktif on public.erp_fiyat_kurallari(aktif, baslangic_tarihi, bitis_tarihi);

-- Başlangıç hesap planı (varsa üzerine yazmaz).
insert into public.erp_hesap_plani(hesap_kodu,hesap_adi,hesap_tipi,aktif) values
('100','KASA','AKTİF',true),
('102','BANKALAR','AKTİF',true),
('120','ALICILAR','AKTİF',true),
('153','TİCARİ MALLAR','AKTİF',true),
('191','İNDİRİLECEK KDV','AKTİF',true),
('320','SATICILAR','PASİF',true),
('391','HESAPLANAN KDV','PASİF',true),
('600','YURTİÇİ SATIŞLAR','GELİR',true),
('621','SATILAN TİCARİ MALLAR MALİYETİ','GİDER',true),
('646','KAMBİYO KÂRLARI','GELİR',true),
('656','KAMBİYO ZARARLARI','GİDER',true),
('770','GENEL YÖNETİM GİDERLERİ','GİDER',true)
on conflict (hesap_kodu) do nothing;

-- Geçiş dönemi RLS politikaları. Güvenli giriş zorunlu hale getirildiğinde hardening migration uygulanmalı.
-- RLS yalnız TABLE / PARTITIONED TABLE üzerinde uygulanır; VIEW nesneleri güvenle atlanır.
do $$
declare
  t text;
  v_relkind "char";
begin
  foreach t in array array['erp_belge_baglantilari','erp_kur_farki_fisleri','erp_sistem_kontrol_log','erp_vade_takip'] loop
    select c.relkind
      into v_relkind
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = t;

    if v_relkind in ('r','p') then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists "pro_erp_gecis_%s" on public.%I', t, t);
      execute format('create policy "pro_erp_gecis_%s" on public.%I for all to anon, authenticated using (true) with check (true)', t, t);
    else
      raise notice '% için RLS atlandı. Relation tipi: %', t, coalesce(v_relkind::text,'yok');
    end if;
  end loop;
end $$;
