-- PRO ERP 2.4.0 - Yedek Parça Araç Kataloğu
-- Normalize araç + parça OEM kataloğu. Mevcut stok/uyumluluk tablolarına dokunmaz.

create table if not exists public.erp_arac_katalog_araclar (
  arac_id bigint generated by default as identity primary key,
  katalog_anahtar text not null unique,
  yillar text,
  uretici text not null,
  yil integer,
  model text not null,
  motor text,
  yakit text,
  motor_kodu text,
  sase text,
  notlar text,
  arac_sahibi text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_erp_arac_katalog_arama
  on public.erp_arac_katalog_araclar(uretici, model, yil, motor_kodu);
create index if not exists idx_erp_arac_katalog_sase
  on public.erp_arac_katalog_araclar(sase);

create table if not exists public.erp_arac_katalog_parcalar (
  parca_id bigint generated by default as identity primary key,
  arac_id bigint not null references public.erp_arac_katalog_araclar(arac_id) on delete cascade,
  kategori_kodu text not null,
  kategori_adi text not null,
  oem_kodu text,
  ham_deger text,
  nitelik text,
  sira integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_arac_katalog_parca_arac
  on public.erp_arac_katalog_parcalar(arac_id, sira);
create index if not exists idx_erp_arac_katalog_parca_oem
  on public.erp_arac_katalog_parcalar(oem_kodu);
create index if not exists idx_erp_arac_katalog_parca_kategori
  on public.erp_arac_katalog_parcalar(kategori_kodu);

-- Tek araç + kategori + OEM tekrarını engeller. NULL OEM nitelik satırları için ham değer kullanılır.
create unique index if not exists uq_erp_arac_katalog_parca
  on public.erp_arac_katalog_parcalar(arac_id, kategori_kodu, coalesce(oem_kodu,''), coalesce(nitelik,''));

-- Arama için sade görünüm.
create or replace view public.erp_arac_katalog_v as
select
  a.arac_id, a.yillar, a.uretici, a.yil, a.model, a.motor, a.yakit,
  a.motor_kodu, a.sase, a.notlar, a.arac_sahibi,
  p.parca_id, p.kategori_kodu, p.kategori_adi, p.oem_kodu,
  p.ham_deger, p.nitelik, p.sira
from public.erp_arac_katalog_araclar a
left join public.erp_arac_katalog_parcalar p on p.arac_id = a.arac_id;

-- Mevcut geçiş güvenlik modeline uyum. Güvenli giriş zorunlu hale geldiğinde authenticated'a daraltılabilir.
do $$
declare t text;
begin
  foreach t in array array['erp_arac_katalog_araclar','erp_arac_katalog_parcalar'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "pro_erp_gecis_%s" on public.%I', t, t);
    execute format('create policy "pro_erp_gecis_%s" on public.%I for all to anon, authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

grant select, insert, update, delete on public.erp_arac_katalog_araclar to anon, authenticated;
grant select, insert, update, delete on public.erp_arac_katalog_parcalar to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant select on public.erp_arac_katalog_v to anon, authenticated;
