-- PRO-ERP Pazaryeri / E-Ticaret Merkezi
create table if not exists public.erp_pazaryeri_kanallari (
 id bigint generated by default as identity primary key, kanal_kodu text not null unique, kanal_adi text not null,
 aktif boolean not null default false, satici_id text, magaza_adi text, api_ayar jsonb not null default '{}'::jsonb,
 stok_rezervi numeric(12,3) not null default 0, fiyat_carpani numeric(10,4) not null default 1,
 komisyon_orani numeric(7,4) not null default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.erp_pazaryeri_urunleri (
 id bigint generated by default as identity primary key, kanal_id bigint references public.erp_pazaryeri_kanallari(id) on delete cascade,
 kanal text, stok_id bigint, stok_kodu text, merchant_sku text, barkod text, urun_adi text, pazaryeri_urun_id text,
 kanal_stok numeric(12,3) default 0, kanal_fiyati numeric(14,4) default 0, liste_fiyati numeric(14,4) default 0,
 komisyon_orani numeric(7,4) default 0, durum text default 'BEKLIYOR', son_senkron timestamptz, hata text,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(kanal_id, merchant_sku));
create table if not exists public.erp_pazaryeri_siparisleri (
 id bigint generated by default as identity primary key, kanal_id bigint references public.erp_pazaryeri_kanallari(id), kanal text,
 siparis_no text not null, pazaryeri_siparis_id text, siparis_tarihi timestamptz default now(), durum text default 'YENI',
 musteri_adi text, telefon text, eposta text, teslimat_adresi jsonb default '{}'::jsonb,
 ara_toplam numeric(14,4) default 0, indirim numeric(14,4) default 0, kargo_tutari numeric(14,4) default 0,
 komisyon_tutari numeric(14,4) default 0, diger_kesinti numeric(14,4) default 0, toplam_tutar numeric(14,4) default 0,
 net_tahsilat numeric(14,4) default 0, kargo_firmasi text, takip_no text, fatura_no text,
 erp_satis_id bigint, ham_veri jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(kanal_id,siparis_no));
create table if not exists public.erp_pazaryeri_siparis_detay (
 id bigint generated by default as identity primary key, siparis_id bigint not null references public.erp_pazaryeri_siparisleri(id) on delete cascade,
 stok_id bigint, merchant_sku text, barkod text, urun_adi text, miktar numeric(12,3) default 1, birim_fiyat numeric(14,4) default 0,
 indirim numeric(14,4) default 0, komisyon numeric(14,4) default 0, maliyet numeric(14,4) default 0, satir_toplam numeric(14,4) default 0);
create table if not exists public.erp_pazaryeri_iadeleri (
 id bigint generated by default as identity primary key, kanal_id bigint references public.erp_pazaryeri_kanallari(id), kanal text,
 siparis_no text, iade_no text, durum text default 'BEKLIYOR', neden text, aciklama text, tutar numeric(14,4) default 0,
 stoga_alindi boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.erp_pazaryeri_senkron_log (
 id bigint generated by default as identity primary key, kanal_id bigint references public.erp_pazaryeri_kanallari(id), islem text not null,
 basarili boolean default true, adet integer default 0, mesaj text, detay jsonb default '{}'::jsonb, created_at timestamptz default now());
create index if not exists idx_pz_siparis_tarih on public.erp_pazaryeri_siparisleri(siparis_tarihi desc);
create index if not exists idx_pz_siparis_durum on public.erp_pazaryeri_siparisleri(durum);
create index if not exists idx_pz_urun_stok on public.erp_pazaryeri_urunleri(stok_id);
create index if not exists idx_pz_iade_siparis on public.erp_pazaryeri_iadeleri(siparis_no);
insert into public.erp_pazaryeri_kanallari(kanal_kodu,kanal_adi,aktif) values
 ('TRENDYOL','Trendyol',false),('HEPSIBURADA','Hepsiburada',false),('N11','n11',false),('AMAZON_TR','Amazon Türkiye',false),('WEB','Web Sitesi',false)
on conflict (kanal_kodu) do nothing;
