-- PRO ERP Kurumsal / Yedek Parça ERP genişletme paketi
-- Mevcut tabloları silmez. CREATE TABLE IF NOT EXISTS kullanır.

create table if not exists public.erp_teklifler (
  teklif_id bigint generated by default as identity primary key,
  belge_no text unique,
  tarih date default current_date,
  cari_unvan text,
  para_birimi text default 'TRY',
  kur numeric(18,6) default 1,
  toplam numeric(18,2) default 0,
  durum text default 'HAZIR',
  gecerlilik_tarihi date,
  aciklama text,
  created_at timestamptz default now()
);

create table if not exists public.erp_hesap_plani (
  hesap_id bigint generated by default as identity primary key,
  hesap_kodu text unique not null,
  hesap_adi text not null,
  hesap_tipi text,
  ust_hesap_kodu text,
  aktif boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.erp_muhasebe_fisleri (
  fis_id bigint generated by default as identity primary key,
  fis_no text unique,
  tarih date default current_date,
  fis_tipi text default 'MAHSUP',
  aciklama text,
  borc_toplam numeric(18,2) default 0,
  alacak_toplam numeric(18,2) default 0,
  durum text default 'TASLAK',
  created_at timestamptz default now(),
  constraint erp_muhasebe_fis_denge check (borc_toplam >= 0 and alacak_toplam >= 0)
);

create table if not exists public.erp_cek_senet (
  evrak_id bigint generated by default as identity primary key,
  evrak_tipi text default 'ÇEK',
  evrak_no text,
  cari_unvan text,
  banka text,
  vade_tarihi date,
  tutar numeric(18,2) default 0,
  para_birimi text default 'TRY',
  durum text default 'PORTFOYDE',
  aciklama text,
  created_at timestamptz default now()
);
create index if not exists idx_erp_cek_senet_vade on public.erp_cek_senet(vade_tarihi);

create table if not exists public.erp_doviz_kurlari (
  kur_id bigint generated by default as identity primary key,
  tarih date default current_date,
  para_birimi text not null,
  alis numeric(18,6) default 0,
  satis numeric(18,6) default 0,
  efektif_alis numeric(18,6) default 0,
  efektif_satis numeric(18,6) default 0,
  kaynak text default 'MANUEL',
  created_at timestamptz default now(),
  unique(tarih, para_birimi)
);

create table if not exists public.erp_e_belgeler (
  ebelge_id bigint generated by default as identity primary key,
  belge_tipi text default 'E-FATURA',
  belge_no text,
  cari_unvan text,
  vergi_no text,
  olusturma_tarihi timestamptz default now(),
  durum text default 'HAZIR',
  entegrator text,
  uuid text,
  hata_mesaji text,
  created_at timestamptz default now()
);

create table if not exists public.erp_satin_alma_talepleri (
  talep_id bigint generated by default as identity primary key,
  talep_no text unique,
  tarih date default current_date,
  talep_eden text,
  depo text,
  oncelik text default 'NORMAL',
  durum text default 'BEKLIYOR',
  aciklama text,
  created_at timestamptz default now()
);

create table if not exists public.erp_onaylar (
  onay_id bigint generated by default as identity primary key,
  onay_tipi text,
  referans_no text,
  olusturma_tarihi timestamptz default now(),
  isteyen text,
  onaylayan text,
  durum text default 'BEKLIYOR',
  aciklama text,
  created_at timestamptz default now()
);

create table if not exists public.erp_seri_lot (
  seri_lot_id bigint generated by default as identity primary key,
  stok_id bigint,
  uretici_kodu text,
  seri_no text,
  lot_no text,
  depo text,
  raf text,
  miktar numeric(18,3) default 1,
  son_kullanma_tarihi date,
  durum text default 'STOKTA',
  olusturma_tarihi timestamptz default now(),
  created_at timestamptz default now()
);
create index if not exists idx_erp_seri_lot_stok on public.erp_seri_lot(stok_id);
create index if not exists idx_erp_seri_lot_seri on public.erp_seri_lot(seri_no);

create table if not exists public.erp_fiyat_kurallari (
  kural_id bigint generated by default as identity primary key,
  kural_adi text not null,
  kapsam_tipi text default 'GENEL',
  kapsam_degeri text,
  iskonto_orani numeric(9,4) default 0,
  kar_orani numeric(9,4) default 0,
  baslangic_tarihi date,
  bitis_tarihi date,
  aktif boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.erp_arac_uyumluluk (
  uyumluluk_id bigint generated by default as identity primary key,
  stok_id bigint,
  uretici_kodu text,
  marka text not null,
  model text not null,
  yil_baslangic integer,
  yil_bitis integer,
  motor text,
  motor_kodu text,
  sasi_notu text,
  aciklama text,
  created_at timestamptz default now()
);
create index if not exists idx_erp_arac_uyumluluk_arama on public.erp_arac_uyumluluk(marka, model, motor_kodu);
create index if not exists idx_erp_arac_uyumluluk_stok on public.erp_arac_uyumluluk(stok_id);

-- Yeni tablolar için RLS. Mevcut ERP'nin opsiyonel giriş yapısıyla uyumlu olacak şekilde
-- anon ve authenticated rolleri CRUD yapabilir. Canlı ortamda güvenli giriş zorunlu hale
-- getirildiğinde 20260812_rls_hardening.sql dosyası ile sadece authenticated rolüne daraltın.
do $$
declare t text;
begin
  foreach t in array array[
    'erp_teklifler','erp_hesap_plani','erp_muhasebe_fisleri','erp_cek_senet',
    'erp_doviz_kurlari','erp_e_belgeler','erp_satin_alma_talepleri','erp_onaylar',
    'erp_seri_lot','erp_fiyat_kurallari','erp_arac_uyumluluk'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "pro_erp_gecis_%s" on public.%I', t, t);
    execute format('create policy "pro_erp_gecis_%s" on public.%I for all to anon, authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

-- Belge satır altyapısı (teklif/proforma, muhasebe ve satın alma talebi)
create table if not exists public.erp_teklif_detay (
  detay_id bigint generated by default as identity primary key,
  teklif_id bigint not null references public.erp_teklifler(teklif_id) on delete cascade,
  stok_id bigint,
  uretici_kodu text,
  urun_adi text,
  miktar numeric(18,3) default 1,
  birim_fiyat numeric(18,4) default 0,
  iskonto_orani numeric(9,4) default 0,
  kdv_orani numeric(9,4) default 20,
  toplam numeric(18,2) default 0,
  created_at timestamptz default now()
);
create index if not exists idx_erp_teklif_detay_teklif on public.erp_teklif_detay(teklif_id);

create table if not exists public.erp_muhasebe_fis_satirlari (
  satir_id bigint generated by default as identity primary key,
  fis_id bigint not null references public.erp_muhasebe_fisleri(fis_id) on delete cascade,
  hesap_kodu text not null,
  aciklama text,
  borc numeric(18,2) default 0,
  alacak numeric(18,2) default 0,
  cari_id bigint,
  belge_no text,
  created_at timestamptz default now(),
  constraint erp_muhasebe_satir_tek_yon check (not (borc > 0 and alacak > 0))
);
create index if not exists idx_erp_muhasebe_satir_fis on public.erp_muhasebe_fis_satirlari(fis_id);
create index if not exists idx_erp_muhasebe_satir_hesap on public.erp_muhasebe_fis_satirlari(hesap_kodu);

create table if not exists public.erp_satin_alma_talep_detay (
  detay_id bigint generated by default as identity primary key,
  talep_id bigint not null references public.erp_satin_alma_talepleri(talep_id) on delete cascade,
  stok_id bigint,
  uretici_kodu text,
  urun_adi text,
  miktar numeric(18,3) default 1,
  mevcut_stok numeric(18,3) default 0,
  minimum_stok numeric(18,3) default 0,
  aciklama text,
  created_at timestamptz default now()
);
create index if not exists idx_erp_satinalma_talep_detay on public.erp_satin_alma_talep_detay(talep_id);

-- Detay tabloları için geçiş RLS politikaları
do $$
declare t text;
begin
  foreach t in array array['erp_teklif_detay','erp_muhasebe_fis_satirlari','erp_satin_alma_talep_detay'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "pro_erp_gecis_%s" on public.%I', t, t);
    execute format('create policy "pro_erp_gecis_%s" on public.%I for all to anon, authenticated using (true) with check (true)', t, t);
  end loop;
end $$;
